version: "3"

services:
  db:
    container_name: mycrud_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - mycrud-data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  mycrud-data:
    external: true